/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class AJoint : SBJoint {
  private HandleRef swigCPtr;

  internal AJoint(IntPtr cPtr, bool cMemoryOwn) : base(BulletSoftBodyPINVOKE.AJoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AJoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AJoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletSoftBodyPINVOKE.delete_AJoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public SWIGTYPE_p_btVector3 m_axis {
    set {
      BulletSoftBodyPINVOKE.AJoint_m_axis_set(swigCPtr, SWIGTYPE_p_btVector3.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletSoftBodyPINVOKE.AJoint_m_axis_get(swigCPtr);
      SWIGTYPE_p_btVector3 ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btVector3(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_AJoint__IControl m_icontrol {
    set {
      BulletSoftBodyPINVOKE.AJoint_m_icontrol_set(swigCPtr, SWIGTYPE_p_AJoint__IControl.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletSoftBodyPINVOKE.AJoint_m_icontrol_get(swigCPtr);
      SWIGTYPE_p_AJoint__IControl ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_AJoint__IControl(cPtr, false);
      return ret;
    } 
  }

  public override void Prepare(float dt, int iterations) {
    BulletSoftBodyPINVOKE.AJoint_Prepare(swigCPtr, dt, iterations);
  }

  public override void Solve(float dt, float sor) {
    BulletSoftBodyPINVOKE.AJoint_Solve(swigCPtr, dt, sor);
  }

  public override void Terminate(float dt) {
    BulletSoftBodyPINVOKE.AJoint_Terminate(swigCPtr, dt);
  }

  public override SWIGTYPE_p_SBJoint__eType___ Type() {
    SWIGTYPE_p_SBJoint__eType___ ret = new SWIGTYPE_p_SBJoint__eType___(BulletSoftBodyPINVOKE.AJoint_Type(swigCPtr), true);
    return ret;
  }

  public AJoint() : this(BulletSoftBodyPINVOKE.new_AJoint(), true) {
  }

}

}
