/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btAlignedObjectArrayLink : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btAlignedObjectArrayLink(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btAlignedObjectArrayLink obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btAlignedObjectArrayLink() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletSoftBodyPINVOKE.delete_btAlignedObjectArrayLink(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btAlignedObjectArrayLink() : this(BulletSoftBodyPINVOKE.new_btAlignedObjectArrayLink__SWIG_0(), true) {
  }

  public btAlignedObjectArrayLink(btAlignedObjectArrayLink otherArray) : this(BulletSoftBodyPINVOKE.new_btAlignedObjectArrayLink__SWIG_1(btAlignedObjectArrayLink.getCPtr(otherArray)), true) {
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

  public int size() {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_size(swigCPtr);
    return ret;
  }

  public Link at(int n) {
    Link ret = new Link(BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_at__SWIG_0(swigCPtr, n), false);
    return ret;
  }

  public void clear() {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_clear(swigCPtr);
  }

  public void pop_back() {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_pop_back(swigCPtr);
  }

  public void resizeNoInitialize(int newsize) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_resizeNoInitialize(swigCPtr, newsize);
  }

  public void resize(int newsize, Link fillData) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_resize__SWIG_0(swigCPtr, newsize, Link.getCPtr(fillData));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void resize(int newsize) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_resize__SWIG_1(swigCPtr, newsize);
  }

  public Link expandNonInitializing() {
    Link ret = new Link(BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_expandNonInitializing(swigCPtr), false);
    return ret;
  }

  public Link expand(Link fillValue) {
    Link ret = new Link(BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_expand__SWIG_0(swigCPtr, Link.getCPtr(fillValue)), false);
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Link expand() {
    Link ret = new Link(BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_expand__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void push_back(Link _Val) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_push_back(swigCPtr, Link.getCPtr(_Val));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

  public int capacity() {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_capacity(swigCPtr);
    return ret;
  }

  public void reserve(int _Count) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_reserve(swigCPtr, _Count);
  }

  public void swap(int index0, int index1) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_swap(swigCPtr, index0, index1);
  }

  public int findBinarySearch(Link key) {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_findBinarySearch(swigCPtr, Link.getCPtr(key));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int findLinearSearch(Link key) {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_findLinearSearch(swigCPtr, Link.getCPtr(key));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void remove(Link key) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_remove(swigCPtr, Link.getCPtr(key));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initializeFromBuffer(SWIGTYPE_p_void buffer, int size, int capacity) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_initializeFromBuffer(swigCPtr, SWIGTYPE_p_void.getCPtr(buffer), size, capacity);
  }

  public void copyFromArray(btAlignedObjectArrayLink otherArray) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayLink_copyFromArray(swigCPtr, btAlignedObjectArrayLink.getCPtr(otherArray));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
