/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btAlignedObjectArrayMaterialPtr : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btAlignedObjectArrayMaterialPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btAlignedObjectArrayMaterialPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btAlignedObjectArrayMaterialPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletSoftBodyPINVOKE.delete_btAlignedObjectArrayMaterialPtr(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btAlignedObjectArrayMaterialPtr() : this(BulletSoftBodyPINVOKE.new_btAlignedObjectArrayMaterialPtr__SWIG_0(), true) {
  }

  public btAlignedObjectArrayMaterialPtr(btAlignedObjectArrayMaterialPtr otherArray) : this(BulletSoftBodyPINVOKE.new_btAlignedObjectArrayMaterialPtr__SWIG_1(btAlignedObjectArrayMaterialPtr.getCPtr(otherArray)), true) {
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

  public int size() {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_size(swigCPtr);
    return ret;
  }

  public Material at(int n) {
    IntPtr cPtr = BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_at__SWIG_0(swigCPtr, n);
    Material ret = (cPtr == IntPtr.Zero) ? null : new Material(cPtr, false);
    return ret;
  }

  public void clear() {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_clear(swigCPtr);
  }

  public void pop_back() {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_pop_back(swigCPtr);
  }

  public void resizeNoInitialize(int newsize) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_resizeNoInitialize(swigCPtr, newsize);
  }

  public void resize(int newsize, Material fillData) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_resize__SWIG_0(swigCPtr, newsize, Material.getCPtr(fillData));
  }

  public void resize(int newsize) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_resize__SWIG_1(swigCPtr, newsize);
  }

  public SWIGTYPE_p_p_Material expandNonInitializing() {
    SWIGTYPE_p_p_Material ret = new SWIGTYPE_p_p_Material(BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_expandNonInitializing(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_p_Material expand(Material fillValue) {
    SWIGTYPE_p_p_Material ret = new SWIGTYPE_p_p_Material(BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_expand__SWIG_0(swigCPtr, Material.getCPtr(fillValue)), false);
    return ret;
  }

  public SWIGTYPE_p_p_Material expand() {
    SWIGTYPE_p_p_Material ret = new SWIGTYPE_p_p_Material(BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_expand__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void push_back(Material _Val) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_push_back(swigCPtr, Material.getCPtr(_Val));
  }

  public int capacity() {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_capacity(swigCPtr);
    return ret;
  }

  public void reserve(int _Count) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_reserve(swigCPtr, _Count);
  }

  public void swap(int index0, int index1) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_swap(swigCPtr, index0, index1);
  }

  public int findBinarySearch(Material key) {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_findBinarySearch(swigCPtr, Material.getCPtr(key));
    return ret;
  }

  public int findLinearSearch(Material key) {
    int ret = BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_findLinearSearch(swigCPtr, Material.getCPtr(key));
    return ret;
  }

  public void remove(Material key) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_remove(swigCPtr, Material.getCPtr(key));
  }

  public void initializeFromBuffer(SWIGTYPE_p_void buffer, int size, int capacity) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_initializeFromBuffer(swigCPtr, SWIGTYPE_p_void.getCPtr(buffer), size, capacity);
  }

  public void copyFromArray(btAlignedObjectArrayMaterialPtr otherArray) {
    BulletSoftBodyPINVOKE.btAlignedObjectArrayMaterialPtr_copyFromArray(swigCPtr, btAlignedObjectArrayMaterialPtr.getCPtr(otherArray));
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
