/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btBU_Simplex1to4 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btBU_Simplex1to4(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btBU_Simplex1to4 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btBU_Simplex1to4() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletCollisionPINVOKE.delete_btBU_Simplex1to4(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btBU_Simplex1to4() : this(BulletCollisionPINVOKE.new_btBU_Simplex1to4__SWIG_0(), true) {
  }

  public btBU_Simplex1to4(SWIGTYPE_p_btVector3 pt0) : this(BulletCollisionPINVOKE.new_btBU_Simplex1to4__SWIG_1(SWIGTYPE_p_btVector3.getCPtr(pt0)), true) {
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public btBU_Simplex1to4(SWIGTYPE_p_btVector3 pt0, SWIGTYPE_p_btVector3 pt1) : this(BulletCollisionPINVOKE.new_btBU_Simplex1to4__SWIG_2(SWIGTYPE_p_btVector3.getCPtr(pt0), SWIGTYPE_p_btVector3.getCPtr(pt1)), true) {
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public btBU_Simplex1to4(SWIGTYPE_p_btVector3 pt0, SWIGTYPE_p_btVector3 pt1, SWIGTYPE_p_btVector3 pt2) : this(BulletCollisionPINVOKE.new_btBU_Simplex1to4__SWIG_3(SWIGTYPE_p_btVector3.getCPtr(pt0), SWIGTYPE_p_btVector3.getCPtr(pt1), SWIGTYPE_p_btVector3.getCPtr(pt2)), true) {
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public btBU_Simplex1to4(SWIGTYPE_p_btVector3 pt0, SWIGTYPE_p_btVector3 pt1, SWIGTYPE_p_btVector3 pt2, SWIGTYPE_p_btVector3 pt3) : this(BulletCollisionPINVOKE.new_btBU_Simplex1to4__SWIG_4(SWIGTYPE_p_btVector3.getCPtr(pt0), SWIGTYPE_p_btVector3.getCPtr(pt1), SWIGTYPE_p_btVector3.getCPtr(pt2), SWIGTYPE_p_btVector3.getCPtr(pt3)), true) {
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    BulletCollisionPINVOKE.btBU_Simplex1to4_reset(swigCPtr);
  }

  public virtual void getAabb(SWIGTYPE_p_btTransform t, SWIGTYPE_p_btVector3 aabbMin, SWIGTYPE_p_btVector3 aabbMax) {
    BulletCollisionPINVOKE.btBU_Simplex1to4_getAabb(swigCPtr, SWIGTYPE_p_btTransform.getCPtr(t), SWIGTYPE_p_btVector3.getCPtr(aabbMin), SWIGTYPE_p_btVector3.getCPtr(aabbMax));
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addVertex(SWIGTYPE_p_btVector3 pt) {
    BulletCollisionPINVOKE.btBU_Simplex1to4_addVertex(swigCPtr, SWIGTYPE_p_btVector3.getCPtr(pt));
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int getNumVertices() {
    int ret = BulletCollisionPINVOKE.btBU_Simplex1to4_getNumVertices(swigCPtr);
    return ret;
  }

  public virtual int getNumEdges() {
    int ret = BulletCollisionPINVOKE.btBU_Simplex1to4_getNumEdges(swigCPtr);
    return ret;
  }

  public virtual void getEdge(int i, SWIGTYPE_p_btVector3 pa, SWIGTYPE_p_btVector3 pb) {
    BulletCollisionPINVOKE.btBU_Simplex1to4_getEdge(swigCPtr, i, SWIGTYPE_p_btVector3.getCPtr(pa), SWIGTYPE_p_btVector3.getCPtr(pb));
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getVertex(int i, SWIGTYPE_p_btVector3 vtx) {
    BulletCollisionPINVOKE.btBU_Simplex1to4_getVertex(swigCPtr, i, SWIGTYPE_p_btVector3.getCPtr(vtx));
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int getNumPlanes() {
    int ret = BulletCollisionPINVOKE.btBU_Simplex1to4_getNumPlanes(swigCPtr);
    return ret;
  }

  public virtual void getPlane(SWIGTYPE_p_btVector3 planeNormal, SWIGTYPE_p_btVector3 planeSupport, int i) {
    BulletCollisionPINVOKE.btBU_Simplex1to4_getPlane(swigCPtr, SWIGTYPE_p_btVector3.getCPtr(planeNormal), SWIGTYPE_p_btVector3.getCPtr(planeSupport), i);
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int getIndex(int i) {
    int ret = BulletCollisionPINVOKE.btBU_Simplex1to4_getIndex(swigCPtr, i);
    return ret;
  }

  public virtual bool isInside(SWIGTYPE_p_btVector3 pt, float tolerance) {
    bool ret = BulletCollisionPINVOKE.btBU_Simplex1to4_isInside(swigCPtr, SWIGTYPE_p_btVector3.getCPtr(pt), tolerance);
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string getName() {
    string ret = BulletCollisionPINVOKE.btBU_Simplex1to4_getName(swigCPtr);
    return ret;
  }

}

}
