/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btCompoundShapeChildData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btCompoundShapeChildData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btCompoundShapeChildData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btCompoundShapeChildData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletCollisionPINVOKE.delete_btCompoundShapeChildData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btTransformFloatData m_transform {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChildData_m_transform_set(swigCPtr, SWIGTYPE_p_btTransformFloatData.getCPtr(value));
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTransformFloatData ret = new SWIGTYPE_p_btTransformFloatData(BulletCollisionPINVOKE.btCompoundShapeChildData_m_transform_get(swigCPtr), true);
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btCollisionShapeData m_childShape {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChildData_m_childShape_set(swigCPtr, SWIGTYPE_p_btCollisionShapeData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btCompoundShapeChildData_m_childShape_get(swigCPtr);
      SWIGTYPE_p_btCollisionShapeData ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionShapeData(cPtr, false);
      return ret;
    } 
  }

  public int m_childShapeType {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChildData_m_childShapeType_set(swigCPtr, value);
    } 
    get {
      int ret = BulletCollisionPINVOKE.btCompoundShapeChildData_m_childShapeType_get(swigCPtr);
      return ret;
    } 
  }

  public float m_childMargin {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChildData_m_childMargin_set(swigCPtr, value);
    } 
    get {
      float ret = BulletCollisionPINVOKE.btCompoundShapeChildData_m_childMargin_get(swigCPtr);
      return ret;
    } 
  }

  public btCompoundShapeChildData() : this(BulletCollisionPINVOKE.new_btCompoundShapeChildData(), true) {
  }

}

}
