/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btCompoundShapeChild : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btCompoundShapeChild(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btCompoundShapeChild obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btCompoundShapeChild() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletCollisionPINVOKE.delete_btCompoundShapeChild(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btTransform m_transform {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChild_m_transform_set(swigCPtr, SWIGTYPE_p_btTransform.getCPtr(value));
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTransform ret = new SWIGTYPE_p_btTransform(BulletCollisionPINVOKE.btCompoundShapeChild_m_transform_get(swigCPtr), true);
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btCollisionShape m_childShape {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChild_m_childShape_set(swigCPtr, SWIGTYPE_p_btCollisionShape.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btCompoundShapeChild_m_childShape_get(swigCPtr);
      SWIGTYPE_p_btCollisionShape ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionShape(cPtr, false);
      return ret;
    } 
  }

  public int m_childShapeType {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChild_m_childShapeType_set(swigCPtr, value);
    } 
    get {
      int ret = BulletCollisionPINVOKE.btCompoundShapeChild_m_childShapeType_get(swigCPtr);
      return ret;
    } 
  }

  public float m_childMargin {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChild_m_childMargin_set(swigCPtr, value);
    } 
    get {
      float ret = BulletCollisionPINVOKE.btCompoundShapeChild_m_childMargin_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_btDbvtNode m_node {
    set {
      BulletCollisionPINVOKE.btCompoundShapeChild_m_node_set(swigCPtr, SWIGTYPE_p_btDbvtNode.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btCompoundShapeChild_m_node_get(swigCPtr);
      SWIGTYPE_p_btDbvtNode ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btDbvtNode(cPtr, false);
      return ret;
    } 
  }

  public btCompoundShapeChild() : this(BulletCollisionPINVOKE.new_btCompoundShapeChild(), true) {
  }

}

}
