/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btConeTwistConstraintData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btConeTwistConstraintData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btConeTwistConstraintData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btConeTwistConstraintData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletDynamicsPINVOKE.delete_btConeTwistConstraintData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btTypedConstraintData m_typeConstraintData {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_typeConstraintData_set(swigCPtr, SWIGTYPE_p_btTypedConstraintData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTypedConstraintData ret = new SWIGTYPE_p_btTypedConstraintData(BulletDynamicsPINVOKE.btConeTwistConstraintData_m_typeConstraintData_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btTransformFloatData m_rbAFrame {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_rbAFrame_set(swigCPtr, SWIGTYPE_p_btTransformFloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTransformFloatData ret = new SWIGTYPE_p_btTransformFloatData(BulletDynamicsPINVOKE.btConeTwistConstraintData_m_rbAFrame_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btTransformFloatData m_rbBFrame {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_rbBFrame_set(swigCPtr, SWIGTYPE_p_btTransformFloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTransformFloatData ret = new SWIGTYPE_p_btTransformFloatData(BulletDynamicsPINVOKE.btConeTwistConstraintData_m_rbBFrame_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public float m_swingSpan1 {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_swingSpan1_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_swingSpan1_get(swigCPtr);
      return ret;
    } 
  }

  public float m_swingSpan2 {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_swingSpan2_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_swingSpan2_get(swigCPtr);
      return ret;
    } 
  }

  public float m_twistSpan {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_twistSpan_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_twistSpan_get(swigCPtr);
      return ret;
    } 
  }

  public float m_limitSoftness {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_limitSoftness_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_limitSoftness_get(swigCPtr);
      return ret;
    } 
  }

  public float m_biasFactor {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_biasFactor_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_biasFactor_get(swigCPtr);
      return ret;
    } 
  }

  public float m_relaxationFactor {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_relaxationFactor_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_relaxationFactor_get(swigCPtr);
      return ret;
    } 
  }

  public float m_damping {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_damping_set(swigCPtr, value);
    } 
    get {
      float ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_damping_get(swigCPtr);
      return ret;
    } 
  }

  public string m_pad {
    set {
      BulletDynamicsPINVOKE.btConeTwistConstraintData_m_pad_set(swigCPtr, value);
    } 
    get {
      string ret = BulletDynamicsPINVOKE.btConeTwistConstraintData_m_pad_get(swigCPtr);
      return ret;
    } 
  }

  public btConeTwistConstraintData() : this(BulletDynamicsPINVOKE.new_btConeTwistConstraintData(), true) {
  }

}

}
