/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btCPUVertexBufferDescriptor : btVertexBufferDescriptor {
  private HandleRef swigCPtr;

  internal btCPUVertexBufferDescriptor(IntPtr cPtr, bool cMemoryOwn) : base(BulletSoftBodyPINVOKE.btCPUVertexBufferDescriptor_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btCPUVertexBufferDescriptor obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btCPUVertexBufferDescriptor() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletSoftBodyPINVOKE.delete_btCPUVertexBufferDescriptor(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public btCPUVertexBufferDescriptor(SWIGTYPE_p_float basePointer, int vertexOffset, int vertexStride) : this(BulletSoftBodyPINVOKE.new_btCPUVertexBufferDescriptor__SWIG_0(SWIGTYPE_p_float.getCPtr(basePointer), vertexOffset, vertexStride), true) {
  }

  public btCPUVertexBufferDescriptor(SWIGTYPE_p_float basePointer, int vertexOffset, int vertexStride, int normalOffset, int normalStride) : this(BulletSoftBodyPINVOKE.new_btCPUVertexBufferDescriptor__SWIG_1(SWIGTYPE_p_float.getCPtr(basePointer), vertexOffset, vertexStride, normalOffset, normalStride), true) {
  }

  public override btVertexBufferDescriptor.BufferTypes getBufferType() {
    btVertexBufferDescriptor.BufferTypes ret = (btVertexBufferDescriptor.BufferTypes)BulletSoftBodyPINVOKE.btCPUVertexBufferDescriptor_getBufferType(swigCPtr);
    return ret;
  }

  public virtual SWIGTYPE_p_float getBasePointer() {
    IntPtr cPtr = BulletSoftBodyPINVOKE.btCPUVertexBufferDescriptor_getBasePointer(swigCPtr);
    SWIGTYPE_p_float ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

}

}
