/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btDbvtProxy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btDbvtProxy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btDbvtProxy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btDbvtProxy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletCollisionPINVOKE.delete_btDbvtProxy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btDbvtNode leaf {
    set {
      BulletCollisionPINVOKE.btDbvtProxy_leaf_set(swigCPtr, SWIGTYPE_p_btDbvtNode.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btDbvtProxy_leaf_get(swigCPtr);
      SWIGTYPE_p_btDbvtNode ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btDbvtNode(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_btDbvtProxy links {
    set {
      BulletCollisionPINVOKE.btDbvtProxy_links_set(swigCPtr, SWIGTYPE_p_p_btDbvtProxy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btDbvtProxy_links_get(swigCPtr);
      SWIGTYPE_p_p_btDbvtProxy ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_btDbvtProxy(cPtr, false);
      return ret;
    } 
  }

  public int stage {
    set {
      BulletCollisionPINVOKE.btDbvtProxy_stage_set(swigCPtr, value);
    } 
    get {
      int ret = BulletCollisionPINVOKE.btDbvtProxy_stage_get(swigCPtr);
      return ret;
    } 
  }

  public btDbvtProxy(SWIGTYPE_p_btVector3 aabbMin, SWIGTYPE_p_btVector3 aabbMax, SWIGTYPE_p_void userPtr, short collisionFilterGroup, short collisionFilterMask) : this(BulletCollisionPINVOKE.new_btDbvtProxy(SWIGTYPE_p_btVector3.getCPtr(aabbMin), SWIGTYPE_p_btVector3.getCPtr(aabbMax), SWIGTYPE_p_void.getCPtr(userPtr), collisionFilterGroup, collisionFilterMask), true) {
    if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
