/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btGeneric6DofSpringConstraintData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btGeneric6DofSpringConstraintData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btGeneric6DofSpringConstraintData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btGeneric6DofSpringConstraintData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletDynamicsPINVOKE.delete_btGeneric6DofSpringConstraintData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btGeneric6DofConstraintData m_6dofData {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_6dofData_set(swigCPtr, btGeneric6DofConstraintData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_6dofData_get(swigCPtr);
      btGeneric6DofConstraintData ret = (cPtr == IntPtr.Zero) ? null : new btGeneric6DofConstraintData(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_int m_springEnabled {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_springEnabled_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_springEnabled_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_float m_equilibriumPoint {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_equilibriumPoint_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_equilibriumPoint_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_float m_springStiffness {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_springStiffness_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_springStiffness_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_float m_springDamping {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_springDamping_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraintData_m_springDamping_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public btGeneric6DofSpringConstraintData() : this(BulletDynamicsPINVOKE.new_btGeneric6DofSpringConstraintData(), true) {
  }

}

}
