/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btGeneric6DofConstraintData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btGeneric6DofConstraintData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btGeneric6DofConstraintData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btGeneric6DofConstraintData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletDynamicsPINVOKE.delete_btGeneric6DofConstraintData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btTypedConstraintData m_typeConstraintData {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_typeConstraintData_set(swigCPtr, SWIGTYPE_p_btTypedConstraintData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTypedConstraintData ret = new SWIGTYPE_p_btTypedConstraintData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_typeConstraintData_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btTransformFloatData m_rbAFrame {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_rbAFrame_set(swigCPtr, SWIGTYPE_p_btTransformFloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTransformFloatData ret = new SWIGTYPE_p_btTransformFloatData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_rbAFrame_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btTransformFloatData m_rbBFrame {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_rbBFrame_set(swigCPtr, SWIGTYPE_p_btTransformFloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btTransformFloatData ret = new SWIGTYPE_p_btTransformFloatData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_rbBFrame_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btVector3FloatData m_linearUpperLimit {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_linearUpperLimit_set(swigCPtr, SWIGTYPE_p_btVector3FloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btVector3FloatData ret = new SWIGTYPE_p_btVector3FloatData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_linearUpperLimit_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btVector3FloatData m_linearLowerLimit {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_linearLowerLimit_set(swigCPtr, SWIGTYPE_p_btVector3FloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btVector3FloatData ret = new SWIGTYPE_p_btVector3FloatData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_linearLowerLimit_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btVector3FloatData m_angularUpperLimit {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_angularUpperLimit_set(swigCPtr, SWIGTYPE_p_btVector3FloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btVector3FloatData ret = new SWIGTYPE_p_btVector3FloatData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_angularUpperLimit_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btVector3FloatData m_angularLowerLimit {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_angularLowerLimit_set(swigCPtr, SWIGTYPE_p_btVector3FloatData.getCPtr(value));
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btVector3FloatData ret = new SWIGTYPE_p_btVector3FloatData(BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_angularLowerLimit_get(swigCPtr), true);
      if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int m_useLinearReferenceFrameA {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_useLinearReferenceFrameA_set(swigCPtr, value);
    } 
    get {
      int ret = BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_useLinearReferenceFrameA_get(swigCPtr);
      return ret;
    } 
  }

  public int m_useOffsetForConstraintFrame {
    set {
      BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_useOffsetForConstraintFrame_set(swigCPtr, value);
    } 
    get {
      int ret = BulletDynamicsPINVOKE.btGeneric6DofConstraintData_m_useOffsetForConstraintFrame_get(swigCPtr);
      return ret;
    } 
  }

  public btGeneric6DofConstraintData() : this(BulletDynamicsPINVOKE.new_btGeneric6DofConstraintData(), true) {
  }

}

}
