/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btGeneric6DofSpringConstraint : btGeneric6DofConstraint {
  private HandleRef swigCPtr;

  internal btGeneric6DofSpringConstraint(IntPtr cPtr, bool cMemoryOwn) : base(BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btGeneric6DofSpringConstraint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btGeneric6DofSpringConstraint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletDynamicsPINVOKE.delete_btGeneric6DofSpringConstraint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public btGeneric6DofSpringConstraint(btRigidBody rbA, btRigidBody rbB, SWIGTYPE_p_btTransform frameInA, SWIGTYPE_p_btTransform frameInB, bool useLinearReferenceFrameA) : this(BulletDynamicsPINVOKE.new_btGeneric6DofSpringConstraint__SWIG_0(btRigidBody.getCPtr(rbA), btRigidBody.getCPtr(rbB), SWIGTYPE_p_btTransform.getCPtr(frameInA), SWIGTYPE_p_btTransform.getCPtr(frameInB), useLinearReferenceFrameA), true) {
    if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public btGeneric6DofSpringConstraint(btRigidBody rbB, SWIGTYPE_p_btTransform frameInB, bool useLinearReferenceFrameB) : this(BulletDynamicsPINVOKE.new_btGeneric6DofSpringConstraint__SWIG_1(btRigidBody.getCPtr(rbB), SWIGTYPE_p_btTransform.getCPtr(frameInB), useLinearReferenceFrameB), true) {
    if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableSpring(int index, bool onOff) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_enableSpring(swigCPtr, index, onOff);
  }

  public void setStiffness(int index, float stiffness) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_setStiffness(swigCPtr, index, stiffness);
  }

  public void setDamping(int index, float damping) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_setDamping(swigCPtr, index, damping);
  }

  public void setEquilibriumPoint() {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_setEquilibriumPoint__SWIG_0(swigCPtr);
  }

  public void setEquilibriumPoint(int index) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_setEquilibriumPoint__SWIG_1(swigCPtr, index);
  }

  public void setEquilibriumPoint(int index, float val) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_setEquilibriumPoint__SWIG_2(swigCPtr, index, val);
  }

  public virtual new void setAxis(SWIGTYPE_p_btVector3 axis1, SWIGTYPE_p_btVector3 axis2) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_setAxis(swigCPtr, SWIGTYPE_p_btVector3.getCPtr(axis1), SWIGTYPE_p_btVector3.getCPtr(axis2));
    if (BulletDynamicsPINVOKE.SWIGPendingException.Pending) throw BulletDynamicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void getInfo2(btConstraintInfo2 info) {
    BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_getInfo2(swigCPtr, btConstraintInfo2.getCPtr(info));
  }

  public override int calculateSerializeBufferSize() {
    int ret = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_calculateSerializeBufferSize(swigCPtr);
    return ret;
  }

  public override string serialize(SWIGTYPE_p_void dataBuffer, SWIGTYPE_p_btSerializer serializer) {
    string ret = BulletDynamicsPINVOKE.btGeneric6DofSpringConstraint_serialize(swigCPtr, SWIGTYPE_p_void.getCPtr(dataBuffer), SWIGTYPE_p_btSerializer.getCPtr(serializer));
    return ret;
  }

}

}
