/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

public enum btHingeFlags {
  BT_HINGE_FLAGS_CFM_STOP = 1,
  BT_HINGE_FLAGS_ERP_STOP = 2,
  BT_HINGE_FLAGS_CFM_NORM = 4
}

}
