/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btMatrix3x3FloatData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btMatrix3x3FloatData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btMatrix3x3FloatData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btMatrix3x3FloatData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LinearMathPINVOKE.delete_btMatrix3x3FloatData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btVector3FloatData m_el {
    set {
      LinearMathPINVOKE.btMatrix3x3FloatData_m_el_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LinearMathPINVOKE.btMatrix3x3FloatData_m_el_get(swigCPtr);
      btVector3FloatData ret = (cPtr == IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public btMatrix3x3FloatData() : this(LinearMathPINVOKE.new_btMatrix3x3FloatData(), true) {
  }

}

}
