/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btScaledTriangleMeshShapeData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btScaledTriangleMeshShapeData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btScaledTriangleMeshShapeData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btScaledTriangleMeshShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletCollisionPINVOKE.delete_btScaledTriangleMeshShapeData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btTriangleMeshShapeData m_trimeshShapeData {
    set {
      BulletCollisionPINVOKE.btScaledTriangleMeshShapeData_m_trimeshShapeData_set(swigCPtr, btTriangleMeshShapeData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btScaledTriangleMeshShapeData_m_trimeshShapeData_get(swigCPtr);
      btTriangleMeshShapeData ret = (cPtr == IntPtr.Zero) ? null : new btTriangleMeshShapeData(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btVector3FloatData m_localScaling {
    set {
      BulletCollisionPINVOKE.btScaledTriangleMeshShapeData_m_localScaling_set(swigCPtr, SWIGTYPE_p_btVector3FloatData.getCPtr(value));
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btVector3FloatData ret = new SWIGTYPE_p_btVector3FloatData(BulletCollisionPINVOKE.btScaledTriangleMeshShapeData_m_localScaling_get(swigCPtr), true);
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public btScaledTriangleMeshShapeData() : this(BulletCollisionPINVOKE.new_btScaledTriangleMeshShapeData(), true) {
  }

}

}
