/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

public enum btSerializationFlags {
  BT_SERIALIZE_NO_BVH = 1,
  BT_SERIALIZE_NO_TRIANGLEINFOMAP = 2,
  BT_SERIALIZE_NO_DUPLICATE_ASSERT = 4
}

}
