/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

public enum btSoftJointBodyType {
  BT_JOINT_SOFT_BODY_CLUSTER = 1,
  BT_JOINT_RIGID_BODY,
  BT_JOINT_COLLISION_OBJECT
}

}
