/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btSoftBodyRigidBodyCollisionConfiguration : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  private SWIGTYPE_p_btCollisionConfiguration swigWrapPtr;

  internal btSoftBodyRigidBodyCollisionConfiguration(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
    swigWrapPtr = new SWIGTYPE_p_btCollisionConfiguration(cPtr, true);
  }

  internal static HandleRef getCPtr(btSoftBodyRigidBodyCollisionConfiguration obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btSoftBodyRigidBodyCollisionConfiguration() {
    Dispose();
  }

  public SWIGTYPE_p_btCollisionConfiguration GetSwigPtr()
  {
      return swigWrapPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletSoftBodyPINVOKE.delete_btSoftBodyRigidBodyCollisionConfiguration(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
        swigWrapPtr = new SWIGTYPE_p_btCollisionConfiguration(IntPtr.Zero, true);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btSoftBodyRigidBodyCollisionConfiguration(SWIGTYPE_p_btDefaultCollisionConstructionInfo constructionInfo) : this(BulletSoftBodyPINVOKE.new_btSoftBodyRigidBodyCollisionConfiguration__SWIG_0(SWIGTYPE_p_btDefaultCollisionConstructionInfo.getCPtr(constructionInfo)), true) {
    if (BulletSoftBodyPINVOKE.SWIGPendingException.Pending) throw BulletSoftBodyPINVOKE.SWIGPendingException.Retrieve();
  }

  public btSoftBodyRigidBodyCollisionConfiguration() : this(BulletSoftBodyPINVOKE.new_btSoftBodyRigidBodyCollisionConfiguration__SWIG_1(), true) {
  }

  public virtual SWIGTYPE_p_btCollisionAlgorithmCreateFunc getCollisionAlgorithmCreateFunc(int proxyType0, int proxyType1) {
    IntPtr cPtr = BulletSoftBodyPINVOKE.btSoftBodyRigidBodyCollisionConfiguration_getCollisionAlgorithmCreateFunc(swigCPtr, proxyType0, proxyType1);
    SWIGTYPE_p_btCollisionAlgorithmCreateFunc ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionAlgorithmCreateFunc(cPtr, false);
    return ret;
  }

}

}
