/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btTriangleMeshShapeData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btTriangleMeshShapeData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btTriangleMeshShapeData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btTriangleMeshShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletCollisionPINVOKE.delete_btTriangleMeshShapeData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btCollisionShapeData m_collisionShapeData {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_collisionShapeData_set(swigCPtr, SWIGTYPE_p_btCollisionShapeData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btTriangleMeshShapeData_m_collisionShapeData_get(swigCPtr);
      SWIGTYPE_p_btCollisionShapeData ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionShapeData(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btStridingMeshInterfaceData m_meshInterface {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_meshInterface_set(swigCPtr, SWIGTYPE_p_btStridingMeshInterfaceData.getCPtr(value));
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_btStridingMeshInterfaceData ret = new SWIGTYPE_p_btStridingMeshInterfaceData(BulletCollisionPINVOKE.btTriangleMeshShapeData_m_meshInterface_get(swigCPtr), true);
      if (BulletCollisionPINVOKE.SWIGPendingException.Pending) throw BulletCollisionPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_btQuantizedBvhFloatData m_quantizedFloatBvh {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_quantizedFloatBvh_set(swigCPtr, SWIGTYPE_p_btQuantizedBvhFloatData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btTriangleMeshShapeData_m_quantizedFloatBvh_get(swigCPtr);
      SWIGTYPE_p_btQuantizedBvhFloatData ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btQuantizedBvhFloatData(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btQuantizedBvhDoubleData m_quantizedDoubleBvh {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_quantizedDoubleBvh_set(swigCPtr, SWIGTYPE_p_btQuantizedBvhDoubleData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btTriangleMeshShapeData_m_quantizedDoubleBvh_get(swigCPtr);
      SWIGTYPE_p_btQuantizedBvhDoubleData ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btQuantizedBvhDoubleData(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btTriangleInfoMapData m_triangleInfoMap {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_triangleInfoMap_set(swigCPtr, SWIGTYPE_p_btTriangleInfoMapData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = BulletCollisionPINVOKE.btTriangleMeshShapeData_m_triangleInfoMap_get(swigCPtr);
      SWIGTYPE_p_btTriangleInfoMapData ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btTriangleInfoMapData(cPtr, false);
      return ret;
    } 
  }

  public float m_collisionMargin {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_collisionMargin_set(swigCPtr, value);
    } 
    get {
      float ret = BulletCollisionPINVOKE.btTriangleMeshShapeData_m_collisionMargin_get(swigCPtr);
      return ret;
    } 
  }

  public string m_pad3 {
    set {
      BulletCollisionPINVOKE.btTriangleMeshShapeData_m_pad3_set(swigCPtr, value);
    } 
    get {
      string ret = BulletCollisionPINVOKE.btTriangleMeshShapeData_m_pad3_get(swigCPtr);
      return ret;
    } 
  }

  public btTriangleMeshShapeData() : this(BulletCollisionPINVOKE.new_btTriangleMeshShapeData(), true) {
  }

}

}
