/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class btTransformDoubleData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btTransformDoubleData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(btTransformDoubleData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~btTransformDoubleData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LinearMathPINVOKE.delete_btTransformDoubleData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public btMatrix3x3DoubleData m_basis {
    set {
      LinearMathPINVOKE.btTransformDoubleData_m_basis_set(swigCPtr, btMatrix3x3DoubleData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LinearMathPINVOKE.btTransformDoubleData_m_basis_get(swigCPtr);
      btMatrix3x3DoubleData ret = (cPtr == IntPtr.Zero) ? null : new btMatrix3x3DoubleData(cPtr, false);
      return ret;
    } 
  }

  public btVector3DoubleData m_origin {
    set {
      LinearMathPINVOKE.btTransformDoubleData_m_origin_set(swigCPtr, btVector3DoubleData.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LinearMathPINVOKE.btTransformDoubleData_m_origin_get(swigCPtr);
      btVector3DoubleData ret = (cPtr == IntPtr.Zero) ? null : new btVector3DoubleData(cPtr, false);
      return ret;
    } 
  }

  public btTransformDoubleData() : this(LinearMathPINVOKE.new_btTransformDoubleData(), true) {
  }

}

}
