/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class BulletCollision {
  public static int gOverlappingPairs {
    set {
      BulletCollisionPINVOKE.gOverlappingPairs_set(value);
    } 
    get {
      int ret = BulletCollisionPINVOKE.gOverlappingPairs_get();
      return ret;
    } 
  }

  public static readonly int ACTIVE_TAG = BulletCollisionPINVOKE.ACTIVE_TAG_get();
  public static readonly int ISLAND_SLEEPING = BulletCollisionPINVOKE.ISLAND_SLEEPING_get();
  public static readonly int WANTS_DEACTIVATION = BulletCollisionPINVOKE.WANTS_DEACTIVATION_get();
  public static readonly int DISABLE_DEACTIVATION = BulletCollisionPINVOKE.DISABLE_DEACTIVATION_get();
  public static readonly int DISABLE_SIMULATION = BulletCollisionPINVOKE.DISABLE_SIMULATION_get();
  public static readonly string btCollisionObjectDataName = BulletCollisionPINVOKE.btCollisionObjectDataName_get();
  public static readonly int TEST_INTERNAL_OBJECTS = BulletCollisionPINVOKE.TEST_INTERNAL_OBJECTS_get();
  public static readonly int USE_DISPATCH_REGISTRY_ARRAY = BulletCollisionPINVOKE.USE_DISPATCH_REGISTRY_ARRAY_get();
  public static readonly int USE_OVERLAP_TEST_ON_REMOVES = BulletCollisionPINVOKE.USE_OVERLAP_TEST_ON_REMOVES_get();
  public static readonly int DBVT_BP_PROFILE = BulletCollisionPINVOKE.DBVT_BP_PROFILE_get();
  public static readonly int DBVT_BP_PREVENTFALSEUPDATE = BulletCollisionPINVOKE.DBVT_BP_PREVENTFALSEUPDATE_get();
  public static readonly int DBVT_BP_ACCURATESLEEPING = BulletCollisionPINVOKE.DBVT_BP_ACCURATESLEEPING_get();
  public static readonly int DBVT_BP_ENABLE_BENCHMARK = BulletCollisionPINVOKE.DBVT_BP_ENABLE_BENCHMARK_get();
  public static readonly int VORONOI_SIMPLEX_MAX_VERTS = BulletCollisionPINVOKE.VORONOI_SIMPLEX_MAX_VERTS_get();
  public static readonly double VORONOI_DEFAULT_EQUAL_VERTEX_THRESHOLD = BulletCollisionPINVOKE.VORONOI_DEFAULT_EQUAL_VERTEX_THRESHOLD_get();
}

}
