/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BulletCSharp {

using System;
using System.Runtime.InteropServices;

public class ConvexH : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConvexH(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ConvexH obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ConvexH() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LinearMathPINVOKE.delete_ConvexH(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ConvexH() : this(LinearMathPINVOKE.new_ConvexH__SWIG_0(), true) {
  }

  public SWIGTYPE_p_btAlignedObjectArrayT_btVector3_t vertices {
    set {
      LinearMathPINVOKE.ConvexH_vertices_set(swigCPtr, SWIGTYPE_p_btAlignedObjectArrayT_btVector3_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LinearMathPINVOKE.ConvexH_vertices_get(swigCPtr);
      SWIGTYPE_p_btAlignedObjectArrayT_btVector3_t ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btAlignedObjectArrayT_btVector3_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btAlignedObjectArrayT_ConvexH__HalfEdge_t edges {
    set {
      LinearMathPINVOKE.ConvexH_edges_set(swigCPtr, SWIGTYPE_p_btAlignedObjectArrayT_ConvexH__HalfEdge_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LinearMathPINVOKE.ConvexH_edges_get(swigCPtr);
      SWIGTYPE_p_btAlignedObjectArrayT_ConvexH__HalfEdge_t ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btAlignedObjectArrayT_ConvexH__HalfEdge_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btAlignedObjectArrayT_btPlane_t facets {
    set {
      LinearMathPINVOKE.ConvexH_facets_set(swigCPtr, SWIGTYPE_p_btAlignedObjectArrayT_btPlane_t.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LinearMathPINVOKE.ConvexH_facets_get(swigCPtr);
      SWIGTYPE_p_btAlignedObjectArrayT_btPlane_t ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btAlignedObjectArrayT_btPlane_t(cPtr, false);
      return ret;
    } 
  }

  public ConvexH(int vertices_size, int edges_size, int facets_size) : this(LinearMathPINVOKE.new_ConvexH__SWIG_1(vertices_size, edges_size, facets_size), true) {
  }

}

}
